<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn> 

    <PackageId>OpenCompote.SGA</PackageId>
    <Version>0.1.0</Version>
    <description>OpenCompote.SGA is a C# library for working with Relics .sga archive files.</description>
    <Authors>vojcermak</Authors>
    <Product>OpenCompote.SGA</Product>

    <PackageProjectUrl>https://vojcermak.github.io/open-compote/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/vojcermak/open-compote</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>sga;relic-sga;relic-entertainment;essence-engine;dawn-of-war;library;archive;modding</PackageTags>
  </PropertyGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <InternalsVisibleTo Include="OpenCompote.SGA.Tests" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
