# Testing if this workflow runs when i trigger it manually.
name: Release

on:
  workflow_dispatch:

jobs:
    # test:
    #     runs-on: ubuntu-latest
    #     steps:
    #       - uses: actions/checkout@v4
    #       - name: Setup .NET
    #         uses: actions/setup-dotnet@v4
    #         with:
    #             dotnet-version: 10.x
    #       - name: Restore dependencies
    #         run: dotnet restore
    #       - name: Build
    #         run: dotnet build --no-restore
    #       - name: Test
    #         run: dotnet test --no-build --verbosity normal
    
    build-package:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
          - uses: actions/checkout@v2
          - name: Setup .NET
            uses: actions/setup-dotnet@v4
            with:
                dotnet-version: 10.x
          - name: Pack
            run: dotnet pack OpenCompote
          - name: Get Version
            id: get-version
            run: |
              VERSION=(dotnet msbuild OpenCompote -getProperty:Version)
              echo "version=$VERSION" >> $GITHUB_OUTPUT
          - name: Create Release
            uses: softprops/action-gh-release@v2
            with:
                tag_name: v${{ steps.get-version.outputs.version }}
                name: Release v${{ steps.get-version.outputs.version }}
