# Testing if this workflow runs when i trigger it manually.
name: Release

on:
  workflow_dispatch:

jobs:
    # test:
    #     runs-on: ubuntu-latest
    #     steps:
    #       - uses: actions/checkout@v4
    #       - name: Setup .NET
    #         uses: actions/setup-dotnet@v4
    #         with:
    #             dotnet-version: 10.x
    #       - name: Restore dependencies
    #         run: dotnet restore
    #       - name: Build
    #         run: dotnet build --no-restore
    #       - name: Test
    #         run: dotnet test --no-build --verbosity normal
    
    build-package:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write  # enable GitHub OIDC token issuance for this job
        steps:
          - uses: actions/checkout@v2
          - name: Setup .NET
            uses: actions/setup-dotnet@v4
            with:
                dotnet-version: 10.x

          - name: Get Version
            id: get-version
            run: |
              VERSION=$(dotnet build OpenCompote -getProperty:Version)
              echo "version=$VERSION" >> $GITHUB_OUTPUT
          - name: Get latest release info
            id: get-notes
            uses: release-flow/keep-a-changelog-action@v2
            with:
                command: query
                version: latest

          - name: Pack
            run: dotnet pack OpenCompote -p:PackageReleaseNotes="${{ steps.get-notes.outputs.release-notes }}"

          - name: Create Release
            uses: softprops/action-gh-release@v2
            with:
                tag_name: OpenCompote_v${{ steps.get-version.outputs.version }}
                name: OpenCompote v${{ steps.get-version.outputs.version }}
                body: ${{ steps.get-notes.outputs.release-notes }}
          - name: NuGet login (OIDC → temp API key)
            uses: NuGet/login@v1
            id: login
            with:
                user: vojcermak
          - name: NuGet push
            run: dotnet nuget push ./OpenCompote/bin/Release/*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
